% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 07-Oct-2019 10:11:25
%
% This script assumes these variables are defined:
%
%   cons_teste_input - input data.
%   Consumo_D_ - target data.
%cons_teste_input=[Consumo_D_1__1 Consumo_D_6__1 Hora];%7.4%
%cons_teste_input=[Consumo_D_6__1 Hora]; %6%
cons_teste_input=[Consumo_D_6__1 Hora M_s_D_1_]; %5.77 ? o melhor ate agr meter novos valores excel
%cons_teste_input=[Consumo_D_6__1 Hora M_s_D_1_ Temperatura_D_1_]; 5.8%

x = cons_teste_input';
t = Consumo_D_';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainlm';  % Levenberg-Marquardt backpropagation.

% Create a Fitting Network
hiddenLayerSize = 10;
net_cons_teste = fitnet(hiddenLayerSize,trainFcn);

% Setup Division of Data for Training, Validation, Testing
net_cons_teste.divideParam.trainRatio = 70/100;
net_cons_teste.divideParam.valRatio = 15/100;
net_cons_teste.divideParam.testRatio = 15/100;

% Train the Network
[net_cons_teste,tr] = train(net_cons_teste,x,t);

% Test the Network
y = net_cons_teste(x);
e = gsubtract(t,y);
performance = perform(net_cons_teste,t,y)

% View the Network
view(net_cons_teste)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotfit(net,x,t)

%calculo dos erros de previs?o%
k=11686; %espa?o temporal de previs?o
forecast=[output];
Xreal=Consumo_D_1_;
actual=[Xreal]';

%%MAPEEEE%
lambdabar1=(1/k)*sum(forecast);
erro1=actual-forecast; %diferen?a entre real e previsto
erroabs1=abs(erro1);
PE1=(erroabs1/lambdabar1)*100;
MAPE1=sum(PE1)/k;

figure;
plot(Xreal,'black','LineWidth',1)
hold on
plot(output,'blue--','LineWidth',1)
axis([0,k,0,60]); 
set(gca,'XTick',0:k/7:k,'fontname','Times','fontsize',14);
set(gca, 'fontname','Times','fontsize',14);
xlabel('Horizonte Temporal (h)','fontname','Times','fontsize',14); 
ylabel('Pre?o (Euro/MWh)','fontname','Times','fontsize',14); 
axis('square');

