% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 15-Oct-2019 10:42:34
%
% This script assumes these variables are defined:
%
%   exportacao_test - input data.
%   Exporta__o_D_ - target data.

%
%   exportacao d-1   (consumo d-1 - prod_total_d_1)  
% exportacao_test =[
%
% target 
%  exportacao d  exporta__o_D_
exportacao_test_1 = [Exporta__o_D_1_ Consumo_D_1__1-prod_total_d_1];

x = exportacao_test_1';
t = Exporta__o_D_';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainlm';  % Levenberg-Marquardt backpropagation.

% Create a Fitting Network
hiddenLayerSize = 5;
net_exp_teste = fitnet(hiddenLayerSize,trainFcn);

% Setup Division of Data for Training, Validation, Testing
net_exp_teste.divideParam.trainRatio = 70/100;
net_exp_teste.divideParam.valRatio = 15/100;
net_exp_teste.divideParam.testRatio = 15/100;

% Train the Network
[net_exp_teste,tr] = train(net_exp_teste,x,t);

% Test the Network
y = net_exp_teste(x);
e = gsubtract(t,y);
performance = perform(net_exp_teste,t,y)

% View the Network
view(net_exp_teste)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotfit(net,x,t)


%calculo dos erros de previs?o%
k=11686; %espa?o temporal de previs?o
forecast= output;
Xreal= Exporta__o_D_1__1;
actual= Xreal';

%%MAPEEEE%
lambdabar1=(1/k)*sum(forecast);
erro1=actual-forecast; %diferen?a entre real e previsto
erroabs1=abs(erro1);
PE1=(erroabs1/lambdabar1)*100;
MAPE1=sum(PE1)/k;



%CALCULO VARIAN?IA ERRO
quoc1=abs(actual-forecast)/lambdabar1;
errosemi=(1/k)*(sum(quoc1));
   
sigmaini=sum((quoc1-errosemi).^2);
 
sigma1=((1/k)*(sigmaini));

%grafico
figure;
plot(Xreal,'blue','LineWidth',1);plot(output,'red','LineWidth',0.3);
hold on


