% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 10-Oct-2019 09:26:23
%
% This script assumes these variables are defined:
%
%   preco_test - input data.
%   Pre_o_D_1_ - target data.
% preco d-6  hora  consumo D-6
% target preco d
% Xreal= preco D+1  Pre_o_D_1_
preco_test=[Pre_o_D_6_ Hora Consumo_D_6_]; %21.0033
%Pre_o_D_

x = preco_test';
t = Pre_o_D_';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainlm';  % Levenberg-Marquardt backpropagation.

% Create a Fitting Network
hiddenLayerSize = 7;
netprecotreino = fitnet(hiddenLayerSize,trainFcn);

% Setup Division of Data for Training, Validation, Testing
netprecotreino.divideParam.trainRatio = 70/100;
netprecotreino.divideParam.valRatio = 15/100;
netprecotreino.divideParam.testRatio = 15/100;

% Train the Network
[netprecotreino,tr] = train(netprecotreino,x,t);

% Test the Network
y = netprecotreino(x);
e = gsubtract(t,y);
performance = perform(netprecotreino,t,y)

% View the Network
view(netprecotreino)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotfit(net,x,t)

  
%calculo dos erros de previs?o%
k=11686; %espa?o temporal de previs?o
forecast= output;
Xreal= Pre_o_D_1_;
actual= Xreal';

%%MAPEEEE%
lambdabar1=(1/k)*sum(forecast);
erro1=actual-forecast; %diferen?a entre real e previsto
erroabs1=abs(erro1);
PE1=(erroabs1/lambdabar1)*100;
MAPE1=sum(PE1)/k;

%CALCULO VARIAN?IA ERRO
%quoc1=abs(actual-forecast)/lambdabar1;
%errosemi=(1/k)*(sum(quoc1));
   
%sigmaini=sum((quoc1-errosemi).^2);
 
%sigma1=((1/k)*(sigmaini));

%grafico
%figure;
%plot(Xreal,'blue','LineWidth',1);plot(output,'red','LineWidth',0.3);
%hold on

